LogFile="/www/%usr%/%dom%/log/access.log"
LogType=W
LogFormat=1
LogSeparator=" "
SiteDomain="%dom%"
HostAliases="www.%dom%"
DNSLookup=2
DirData="/www/%usr%/%dom%/awstats/"
DirCgi="/awstats"
DirIcons="/awstatsicons"
AllowToUpdateStatsFromBrowser=0
AllowFullYearView=3
AllowAccessFromWebToAuthenticatedUsersOnly=1
CreateDirDataIfNotExists=1
BuildHistoryFormat=text
BuildReportFormat=html
PurgeLogFile=0
ArchiveLogRecords=1
ValidHTTPCodes="200 304"
URLWithQuery=1
URLReferrerWithQuery=1
LoadPlugin="tooltips"
LoadPlugin="decodeutfkeys
